# Generate Caddyfile.generated from employee-portal .env (ORIGIN + DRIVE_ORIGIN).

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot '.env'
$outputPath = Join-Path $repoRoot 'Caddyfile.generated'

. (Join-Path $PSScriptRoot 'lib\read-dotenv.ps1')

$envVars = Read-DotEnv $envPath

$portalOrigin = Get-EnvValue $envVars @('ORIGIN', 'PORTAL_ORIGIN')
$driveOrigin = Get-EnvValue $envVars @('DRIVE_ORIGIN')
$portalUpstream = Get-EnvValue $envVars @('CADDY_PORTAL_UPSTREAM')
$driveUpstream = Get-EnvValue $envVars @('CADDY_DRIVE_UPSTREAM')
$caddyTls = Get-EnvValue $envVars @('CADDY_TLS')

if (-not $portalOrigin) {
	throw 'Set ORIGIN in .env (portal public URL, e.g. http://portal.local.test or https://phh.com).'
}
if (-not $driveOrigin) {
	throw 'Set DRIVE_ORIGIN in .env (drive public URL, e.g. http://drive.local.test or https://office.drive.phh.com).'
}

if (-not $portalUpstream) { $portalUpstream = 'localhost:1027' }
if (-not $driveUpstream) { $driveUpstream = 'localhost:1025' }

$portalBlock = Get-CaddySiteBlock -Origin $portalOrigin -Upstream $portalUpstream -TlsMode $caddyTls
$driveBlock = Get-CaddySiteBlock -Origin $driveOrigin -Upstream $driveUpstream -TlsMode $caddyTls

$content = @"
# Generated by scripts/render-caddyfile.ps1 - do not edit by hand.
# Source: .env (ORIGIN, DRIVE_ORIGIN, CADDY_*)

{
	admin off
}

$portalBlock

$driveBlock
"@

Set-Content -Path $outputPath -Value $content.TrimEnd() -Encoding utf8
Write-Host "Wrote $outputPath"
Write-Host "  Portal: $portalOrigin -> $portalUpstream"
Write-Host "  Drive:  $driveOrigin -> $driveUpstream"
