# Generate Caddyfile.generated from employee-portal .env (ORIGIN + DRIVE_ORIGIN + optional DOCS_ORIGIN).

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot '.env'
$outputPath = Join-Path $repoRoot 'Caddyfile.generated'

. (Join-Path $PSScriptRoot 'lib\read-dotenv.ps1')

$envVars = Read-DotEnv $envPath

$portalOrigin = Get-EnvValue $envVars @('ORIGIN', 'PORTAL_ORIGIN')
$driveOrigin = Get-EnvValue $envVars @('DRIVE_ORIGIN')
$docsOrigin = Get-EnvValue $envVars @('DOCS_ORIGIN')
$orderResendOrigin = Get-EnvValue $envVars @('ORDER_RESEND_ORIGIN')
$portalUpstream = Get-EnvValue $envVars @('CADDY_PORTAL_UPSTREAM')
$driveUpstream = Get-EnvValue $envVars @('CADDY_DRIVE_UPSTREAM')
$docsUpstream = Get-EnvValue $envVars @('CADDY_DOCS_UPSTREAM')
$orderResendUpstream = Get-EnvValue $envVars @('CADDY_ORDER_RESEND_UPSTREAM')
$caddyTls = Get-EnvValue $envVars @('CADDY_TLS')

if (-not $portalOrigin) {
	throw 'Set ORIGIN in .env (portal public URL, e.g. http://portal.local.test or https://phh.com).'
}
if (-not $driveOrigin) {
	throw 'Set DRIVE_ORIGIN in .env (drive public URL, e.g. http://drive.local.test or https://office.drive.phh.com).'
}

if (-not $portalUpstream) { $portalUpstream = 'localhost:1027' }
if (-not $driveUpstream) { $driveUpstream = 'localhost:1025' }
if (-not $docsUpstream) { $docsUpstream = 'localhost:1026' }

$portalBlock = Get-CaddySiteBlock -Origin $portalOrigin -Upstream $portalUpstream -TlsMode $caddyTls
$driveBlock = Get-CaddySiteBlock -Origin $driveOrigin -Upstream $driveUpstream -TlsMode $caddyTls

$docsBlock = ''
if ($docsOrigin) {
	$docsBlock = Get-CaddySiteBlock -Origin $docsOrigin -Upstream $docsUpstream -TlsMode $caddyTls
}

$orderResendBlock = ''
if ($orderResendOrigin) {
	if (-not $orderResendUpstream) { $orderResendUpstream = 'localhost:6002' }
	$orderResendBlock = Get-CaddySiteBlock -Origin $orderResendOrigin -Upstream $orderResendUpstream -TlsMode $caddyTls
}

$content = @"
# Generated by scripts/render-caddyfile.ps1 - do not edit by hand.
# Source: .env (ORIGIN, DRIVE_ORIGIN, DOCS_ORIGIN, ORDER_RESEND_ORIGIN, CADDY_*)

{
	admin off
}

$portalBlock

$driveBlock
"@

if ($docsBlock) {
	$content += "`n`n$docsBlock"
}

if ($orderResendBlock) {
	$content += "`n`n$orderResendBlock"
}

Set-Content -Path $outputPath -Value $content.TrimEnd() -Encoding utf8
Write-Host "Wrote $outputPath"
Write-Host "  Portal: $portalOrigin -> $portalUpstream"
Write-Host "  Drive:  $driveOrigin -> $driveUpstream"
if ($docsOrigin) {
	Write-Host "  Docs:   $docsOrigin -> $docsUpstream"
}
if ($orderResendOrigin) {
	Write-Host "  OrderResend: $orderResendOrigin -> $orderResendUpstream"
}
